version: '3.3'
services:
  deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - .:/app
    stdin_open: true
    tty: true